# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "basebox_4640"
  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/acit_admin_id_rsa"

  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 50080
    todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    todoapp.vm.provision "file", source: "./files/nginx.conf", destination: "/home/admin/nginx.conf"
    todoapp.vm.provision "file", source: "./files/database.js", destination: "/home/admin/database.js"
    todoapp.vm.provision "file", source: "./files/todoapp.service", destination: "/home/admin/todoapp.service"
    todoapp.vm.provision "shell" do |shell|
      shell.path = "provision.sh"
    end

    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
      vb.linked_clone = true
    end
  end

# Enable provisioning with a shell script. Additional provisioners such as
# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
# documentation for more information about their specific syntax and use.
#  config.vm.provision "shell", inline: <<-SHELL
#    setenforce 0
#    yum -y install nginx
#   systemctl start nginx
#  SHELL
end
