---
- name: Install NGINX
  become: yes
  package:
    name: nginx
    state: installed
- name: Enable and start NGINX
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started
- name: Copy the NGINX config file
  become: yes
  template:
    src: nginxconf.j2
    dest: /etc/nginx/nginx.conf