---
- name: Disable SELinux
  become: yes
  selinux:
    state: disabled
- include_role:
    name: security
- include_role:
    name: git
- include_role:
    name: nginx
- include_role:
    name: nodejs
- include_role:
    name: mongo